### ISSUE TITLE
install part

### ISSUE THREAD

**Issue by hyperov** [devmuaz/awesome_dio_interceptor#2]
Hi,
this looks very good but looks like you forgot to add the part about how to install the package so we can use it.

**Comment by devmuaz** [comment]
Hi @hyperov,
Thanks for opening the issue, it has been fixed in `v0.0.2+4`, commit [#2dceeee](https://github.com/devmuaz/awesome_dio_interceptor/commit/2dceeee4b5399d00a74dfb407afc80533d4fe226)

Thank You 🙏🏼
