### ISSUE TITLE
Interceptoor Loggers aren't displaying.

### ISSUE THREAD

**Issue by levi956** [devmuaz/awesome_dio_interceptor#4]
Package version v1.0.0
Dio version v5.3.2
IDE - Visual Studio Code

Flutter version 3.13.0

The interceptors aren't displaying on the debug console on VScode anymore.

**Comment by devmuaz** [comment]
Hi @levi956,

Are running your app using "Start Debugging"? the `log` function only works within the debugging mode so if you're running your app without debugging it won't work!

**Comment by levi956** [comment]
Oh mind me, thank you. I hadn't realized I was not running on debug mode.
