### ISSUE TITLE
Using the package with Dart only code

### ISSUE THREAD

**Issue by masreplay** [devmuaz/awesome_dio_interceptor#6]
https://github.com/devmuaz/awesome-dio-interceptor/blob/f391d4ef687833635fccf5ea112fd25be1c287b6/pubspec.yaml#L8

**Comment by devmuaz** [comment]
Hi @masreplay,

Thanks for letting me know about this matter, it has been fixed in `v1.2.0` (currently under processing). Now it supports both `dart-only` and `flutter` projects.

I'm gonna be closing this issue but feel free to reopen it for any further details.
Thanks again!
